### ISSUE TITLE
Why the SPI.h and this footprint a little heavy  IMO

### ISSUE THREAD

**Issue by ebobtron** [Andy4495/USB_Host_ASCII_Keyboard#1]
The Library functions for the USB_Host_Shield_Library_2.0 have a smaller foot print 25% on my little UNO Board  your version here 39%.
Also your script as the other include SPI.h   Why?  Works without it..

Adding keys is pretty easy in the "USB_Host_Shield_Library_2.0" code.

Thanks for the example, it does work well.

**Comment by ebobtron** [comment]
> smaller foot print 25% on my little UNO Board

Sorry it looks like 29%

**Comment by Andy4495** [comment]
I'm not sure what your point is. This is just a sketch based on the USB Host Shield library (https://github.com/felis/USB_Host_Shield_2.0). It meets my needs for interfacing a modern USB keyboard with a retro computer I am working on. 

Yes, the `#include <SPI.h>` directive is superfluous, but that doesn't have an impact on the compilation.
